package docgen_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/gookit/gcli/v3"
	"github.com/gookit/gcli/v3/docgen"
	"github.com/gookit/gcli/v3/gflag"
	"github.com/gookit/goutil/x/assert"
)

// newTestApp 构造一个含选项/参数/示例/子命令的小 app, 供各文档生成用例复用。
func newTestApp() *gcli.App {
	app := gcli.NewApp(func(a *gcli.App) {
		a.Name = "demoapp"
		a.Desc = "the demo app for docgen test"
	})

	sub := &gcli.Command{
		Name: "child",
		Desc: "this is a child command",
		Func: func(c *gcli.Command, _ []string) error { return nil },
	}

	c := &gcli.Command{
		Name:     "demo",
		Desc:     "this is a demo command for test",
		Help:     "long help message for demo command",
		Examples: "<cyan>{$fullCmd} --name tom arg0 arg1</> # run the demo\n" +
			"<cyan>{$fullCmd} --name tom -v arg0</> # verbose run",
		Subs:     []*gcli.Command{sub},
		Config: func(c *gcli.Command) {
			var name string
			var verbose bool
			c.StrOpt2(&name, "name,n", "the name option", gflag.WithRequired())
			c.BoolOpt2(&verbose, "verbose,v", "the verbose bool option")

			c.AddArg("file", "the required input file", true)
			c.AddArg("others", "the arrayed args", false, true)
		},
		Func: func(c *gcli.Command, _ []string) error { return nil },
	}

	app.Add(c)
	return app
}

func TestCmdMarkdown(t *testing.T) {
	app := newTestApp()
	c := app.GetCommand("demo")
	assert.NotNil(t, c)

	md := docgen.CmdMarkdown(c)

	// 注意: c.Path() 不含 app 名, 顶层命令路径即命令名 "demo"
	assert.StrContains(t, md, "# demo")
	assert.StrContains(t, md, "demo command for test")
	assert.StrContains(t, md, "## Synopsis")
	assert.StrContains(t, md, "## Options")
	assert.StrContains(t, md, "--name")
	assert.StrContains(t, md, "## Arguments")
	assert.StrContains(t, md, "others...")
	assert.StrContains(t, md, "## Examples")
	// Examples: 颜色标签被清除, 内置变量 {$fullCmd} 被渲染
	assert.NotContains(t, md, "<cyan>")
	assert.NotContains(t, md, "{$fullCmd}")
	assert.StrContains(t, md, "demo --name tom arg0 arg1")
	// Examples: 多行保留(代码块内两行示例均在)
	assert.StrContains(t, md, "demo --name tom -v arg0")
	assert.StrContains(t, md, "## SubCommands")
	// 子命令链接文件名应与 tree 命名规则一致
	assert.StrContains(t, md, "demo_child.md")
	assert.StrContains(t, md, "Auto generated by gcli docgen.")
}

func TestAppMarkdown(t *testing.T) {
	app := newTestApp()
	md := docgen.AppMarkdown(app)

	assert.StrContains(t, md, "# demoapp")
	assert.StrContains(t, md, "the demo app for docgen test")
	// 应用版本信息
	assert.StrContains(t, md, "**Version**")
	assert.StrContains(t, md, "## Commands")
	assert.StrContains(t, md, "demo.md")
}

func TestCmdMan(t *testing.T) {
	app := newTestApp()
	c := app.GetCommand("demo")
	assert.NotNil(t, c)

	man := docgen.CmdMan(c)

	assert.StrContains(t, man, ".TH")
	assert.StrContains(t, man, ".SH NAME")
	assert.StrContains(t, man, ".SH SYNOPSIS")
	assert.StrContains(t, man, ".SH DESCRIPTION")
	assert.StrContains(t, man, ".SH OPTIONS")
	assert.StrContains(t, man, ".SH ARGUMENTS")
	assert.StrContains(t, man, ".SH EXAMPLES")
	// --name 需被转义为 \-\-name
	assert.StrContains(t, man, "\\-\\-name")
	// Examples 多行保留: 用 .nf/.fi 区块逐行输出, 两行示例均在且未被折叠成一行
	assert.StrContains(t, man, ".nf")
	assert.StrContains(t, man, ".fi")
	assert.StrContains(t, man, "demo \\-\\-name tom arg0 arg1 # run the demo")
	assert.StrContains(t, man, "demo \\-\\-name tom \\-v arg0 # verbose run")
}

func TestManTree(t *testing.T) {
	app := newTestApp()
	dir := t.TempDir()

	err := docgen.ManTree(app, dir)
	assert.NoErr(t, err)

	_, err = os.Stat(filepath.Join(dir, "demo.1"))
	assert.NoErr(t, err)
	_, err = os.Stat(filepath.Join(dir, "demo_child.1"))
	assert.NoErr(t, err)
}

func TestMarkdownTree(t *testing.T) {
	app := newTestApp()
	dir := t.TempDir()

	err := docgen.MarkdownTree(app, dir)
	assert.NoErr(t, err)

	_, err = os.Stat(filepath.Join(dir, "index.md"))
	assert.NoErr(t, err)
	_, err = os.Stat(filepath.Join(dir, "demo.md"))
	assert.NoErr(t, err)
	_, err = os.Stat(filepath.Join(dir, "demo_child.md"))
	assert.NoErr(t, err)
}
