// Package docgen 提供把 gcli 命令/应用导出为 markdown 与 man page(roff) 文档的能力。
//
// 对标 cobra 的 cobra/doc(GenMarkdownTree/GenManTree)，纯新增、零破坏，仅依赖 gcli 公开内省 API。
package docgen

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/gookit/color"
	"github.com/gookit/gcli/v3"
	"github.com/gookit/gcli/v3/gflag"
)

// genTip is the auto-generated footer marker.
const genTip = "> Auto generated by gcli docgen."

// renderText 渲染命令文本用于文档输出: 展开内置变量({$fullCmd}/{$binName}/...)并清除颜色标签
// (如 <cyan>...</>)。命令需已初始化(经 app 运行/添加)变量才会展开。
func renderText(c *gcli.Command, s string) string {
	if s == "" {
		return ""
	}
	return color.ClearTag(c.ReplacePairs(s))
}

// cmdFileName 计算命令的文档文件名(不含扩展名)。
// 规则: 命令全路径以 `_` 连接, 如 `cliapp remote add` -> `cliapp_remote_add`。
func cmdFileName(c *gcli.Command) string {
	return strings.ReplaceAll(c.Path(), " ", "_")
}

// cleanLine 去除换行, 用于表格/单行场景, 避免破坏 markdown 结构。
func cleanLine(s string) string {
	s = strings.ReplaceAll(s, "\r\n", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	return strings.TrimSpace(s)
}

// escapeTableCell 转义 markdown 表格单元格内容: `|` -> `\|`, 并去掉换行。
func escapeTableCell(s string) string {
	s = cleanLine(s)
	return strings.ReplaceAll(s, "|", "\\|")
}

// sortedOptNames 返回命令选项名(已排序), 保证输出稳定。
func sortedOptNames(opts map[string]*gflag.CliOpt) []string {
	names := make([]string, 0, len(opts))
	for name := range opts {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// optHelpName 渲染选项名单元: 短名在前(逗号分隔), 长名 `--name`。eg: `-n, --name`。
func optHelpName(opt *gflag.CliOpt) string {
	var sb strings.Builder
	for _, s := range opt.Shorts {
		sb.WriteString("-")
		sb.WriteString(s)
		sb.WriteString(", ")
	}
	sb.WriteString("--")
	sb.WriteString(opt.Name)
	return sb.String()
}

// CmdMarkdown 渲染单个命令为 markdown 文档(cobra 风格)。
func CmdMarkdown(c *gcli.Command) string {
	var buf strings.Builder

	// 标题 + 描述
	buf.WriteString("# " + c.Path() + "\n\n")
	if c.Desc != "" {
		buf.WriteString(cleanLine(renderText(c, c.Desc)) + "\n\n")
	}

	// 长帮助 -> Synopsis
	if c.Help != "" {
		buf.WriteString("## Synopsis\n\n")
		buf.WriteString(renderText(c, c.Help) + "\n\n")
	}

	// 用法代码块
	buf.WriteString("```\n")
	buf.WriteString(c.Path() + " [--options ...] [arguments ...]\n")
	buf.WriteString("```\n\n")

	// 别名
	if len(c.Aliases) > 0 {
		buf.WriteString("**Aliases**: `" + c.Aliases.String() + "`\n\n")
	}

	// Options 表(跳过 Hidden 选项)
	opts := c.Opts()
	if hasVisibleOpts(opts) {
		buf.WriteString("## Options\n\n")
		buf.WriteString("Option | Type | Default | Required | Description\n")
		buf.WriteString("-------|------|---------|----------|------------\n")
		for _, name := range sortedOptNames(opts) {
			opt := opts[name]
			if opt.Hidden {
				continue
			}
			required := "No"
			if opt.Required {
				required = "Yes"
			}
			buf.WriteString(fmt.Sprintf("`%s` | %s | %s | %s | %s\n",
				escapeTableCell(optHelpName(opt)),
				escapeTableCell(opt.TypeName()),
				escapeTableCell(opt.DValue().String()),
				required,
				escapeTableCell(renderText(c, opt.Desc)),
			))
		}
		buf.WriteString("\n")
	}

	// Arguments 表
	args := c.Args()
	if len(args) > 0 {
		buf.WriteString("## Arguments\n\n")
		buf.WriteString("Argument | Required | Description\n")
		buf.WriteString("---------|----------|------------\n")
		for _, arg := range args {
			name := arg.Name
			if arg.Arrayed {
				name += "..."
			}
			required := "No"
			if arg.Required {
				required = "Yes"
			}
			buf.WriteString(fmt.Sprintf("`%s` | %s | %s\n",
				escapeTableCell(name), required, escapeTableCell(renderText(c, arg.Desc)),
			))
		}
		buf.WriteString("\n")
	}

	// Examples: 渲染内置变量并清除颜色标签(保留多行)
	if c.Examples != "" {
		buf.WriteString("## Examples\n\n")
		buf.WriteString("```\n")
		buf.WriteString(strings.Trim(renderText(c, c.Examples), "\n") + "\n")
		buf.WriteString("```\n\n")
	}

	// SubCommands -> 相对链接(文件名与 MarkdownTree 一致)
	subs := c.Commands()
	if len(subs) > 0 {
		buf.WriteString("## SubCommands\n\n")
		names := make([]string, 0, len(subs))
		for name := range subs {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			sub := subs[name]
			buf.WriteString(fmt.Sprintf("- [%s](%s.md) - %s\n",
				sub.Name, cmdFileName(sub), cleanLine(renderText(sub, sub.Desc))))
		}
		buf.WriteString("\n")
	}

	buf.WriteString(genTip + "\n")
	return buf.String()
}

// hasVisibleOpts 判断是否存在非 Hidden 选项。
func hasVisibleOpts(opts map[string]*gflag.CliOpt) bool {
	for _, opt := range opts {
		if !opt.Hidden {
			return true
		}
	}
	return false
}

// AppMarkdown 渲染应用概览文档: 标题/描述 + 顶层命令列表(含相对链接)。
func AppMarkdown(app *gcli.App) string {
	var buf strings.Builder

	buf.WriteString("# " + app.Name + "\n\n")
	if app.Desc != "" {
		buf.WriteString(cleanLine(color.ClearTag(app.ReplacePairs(app.Desc))) + "\n\n")
	}
	// 应用版本信息
	if app.Version != "" {
		buf.WriteString("**Version**: " + app.Version + "\n\n")
	}

	cmds := app.Commands()
	if len(cmds) > 0 {
		buf.WriteString("## Commands\n\n")
		names := make([]string, 0, len(cmds))
		for name := range cmds {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			c := cmds[name]
			buf.WriteString(fmt.Sprintf("- [%s](%s.md) - %s\n",
				name, cmdFileName(c), cleanLine(renderText(c, c.Desc))))
		}
		buf.WriteString("\n")
	}

	buf.WriteString(genTip + "\n")
	return buf.String()
}

// MarkdownTree 在 dir 下为每个命令(含子命令递归)写一个 `.md`, 另写 `index.md`(= AppMarkdown)。
func MarkdownTree(app *gcli.App, dir string) error {
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	// 写应用概览
	indexFile := filepath.Join(dir, "index.md")
	if err := os.WriteFile(indexFile, []byte(AppMarkdown(app)), 0644); err != nil {
		return err
	}

	// 递归写每个命令文档
	for _, c := range app.Commands() {
		if err := writeCmdMarkdown(c, dir); err != nil {
			return err
		}
	}
	return nil
}

// writeCmdMarkdown 递归写单个命令及其子命令的 markdown 文件。
func writeCmdMarkdown(c *gcli.Command, dir string) error {
	file := filepath.Join(dir, cmdFileName(c)+".md")
	if err := os.WriteFile(file, []byte(CmdMarkdown(c)), 0644); err != nil {
		return err
	}

	for _, sub := range c.Commands() {
		if err := writeCmdMarkdown(sub, dir); err != nil {
			return err
		}
	}
	return nil
}
