name: action-tests
on:
  pull_request:
    paths:
      - 'go.mod'
      - '**.go'
      - '**.yml'
  push:
    paths:
      - 'go.mod'
      - '**.go'
      - '**.yml'

jobs:

  test:
    name: Test on go ${{ matrix.go_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [1.18, 1.19, '1.20']

    steps:
    - name: Check out codes
      uses: actions/checkout@v4

    - name: Setup Go Faster
      uses: WillAbides/setup-go-faster@v1.14.0
      timeout-minutes: 3
      with:
        go-version: ${{ matrix.go_version }}

    - name: Revive check
      uses: morphy2k/revive-action@v2.7.2
      if: ${{ matrix.os == 'ubuntu-latest' }}
      with:
        # Exclude patterns, separated by semicolons (optional)
        exclude: "./internal/..."

    - name: Run staticcheck
      uses: reviewdog/action-staticcheck@v1
      if: ${{ github.event_name == 'pull_request'}}
      with:
        github_token: ${{ secrets.github_token }}
        # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
        reporter: github-pr-check
        # Report all results. [added,diff_context,file,nofilter].
        filter_mode: added
        # Exit with 1 when it find at least one finding.
        fail_on_error: true

    - name: Run tests
      run: go test -v -cover ./...
